# @name get-all-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------Boundary--

###

# @name create-video-transcription
POST http://localhost:3333/videos/ead59d5a-028d-4190-b075-32a0e323c3a0/transcription
Content-Type: application/json

{
    "prompt": "aula, português"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/generate-completion
Content-Type: application/json

{
    "videoId": "ead59d5a-028d-4190-b075-32a0e323c3a0",
    "template": "Gere um resumo da transcrição do vídeo a seguir: ''' {transcription} '''",
    "temperature": 0
}
